#!/bin/sh
# generated by chef, changes will be overwritten

  export HADOOP_CLASSPATH="/etc/tez/conf.chef:/usr/lib/tez/*:/usr/lib/tez/lib/*:$HADOOP_CLASSPATH"
  export HADOOP_JMX_BASE="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false"
  export HADOOP_NAMENODE_OPTS="$HADOOP_JMX_BASE -Dcom.sun.management.jmxremote.port=8004"
  export HADOOP_SECONDARYNAMENODE_OPTS="$HADOOP_JMX_BASE -Dcom.sun.management.jmxremote.port=8005"
  export HADOOP_DATANODE_OPTS="$HADOOP_JMX_BASE -Dcom.sun.management.jmxremote.port=8006"
  export HADOOP_MAPRED_HOME="/usr/lib/hadoop-mapreduce"
  export HADOOP_SECURE_DN_USER="hdfs"
  export HADOOP_SECURE_DN_PID_DIR="/var/run/hadoop-hdfs"
  export HADOOP_SECURE_DN_LOG_DIR="/var/log/hadoop-hdfs"
  export JAVA_HOME="/usr/lib/jvm/java"
  export HADOOP_LOG_DIR="/data/logs/hadoop-hdfs"
